# Тестовые API-запросы

@baseUrl = http://localhost:5000

GET {{baseUrl}}/ads/1
Content-Type: application/json

###

# Создание объявления
POST {{baseUrl}}/ads/
Content-Type: application/json

{
    "title": "Объявление 1",
    "description": "Просто объявление",
    "owner": "Продавец 1"
}

###

# Изменение объявления
PATCH {{baseUrl}}/ads/1
Content-Type: application/json

{
    "title": "Обновление",
    "description": ""
}

###

# Удаление объявления
DELETE {{baseUrl}}/ads/1